[build]
  publish = "dist"
  command = "npm run build"

# Specific redirects first (higher priority)
[[redirects]]
  from = "/login/*"
  to = "/login"
  status = 301
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/choose-action"
  status = 302

# SPA fallback (catch-all)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 